# Generated by Django 3.1 on 2020-09-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messege',
            new_name='message',
        ),
    ]
