# Generated by Django 3.1 on 2020-09-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200919_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men Eyewear', 'Men Eyewear'), ('Women Eyewear', 'Women Eyewear')], default='', max_length=50),
        ),
    ]
