# Generated by Django 3.1.2 on 2020-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201019_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fresh_Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Men Eyewear', 'Men Eyewear'), ('Women Eyewear', 'Women Eyewear')], default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='products/images')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
